### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Wabtyy** [dumbasPL/csgo-checker#28]
When im importing the accounts, nothink happens. there is just a blue loading bar on every account. i waited over 5 h but nothing happend.

**Comment by dumbasPL** [comment]
In order to pinpoint the problem I would need an error log. 

(I'm assuming you're on Windows)
To get the debug log you need to start the app with the `--enable-logging` parameter. The easiest way to do this is to edit the desktop shortcut and add ` --enable-logging` to the very end of the `Target` field (make sure to add it after the `"` if there is one at the end and make sure there is a space before the argument.

Alternatively open a terminal in the install location (`C:\Users\<USER>\AppData\Local\Programs\csgo-checker` by default) and run `"CSGO account checker.exe" --enable-logging`

This will open an additional console or use the existing one if you went with the terminal method.

I want you to remove all accounts, restart the app, add a single account by hand, and observe the log output.

Ensure there is nothing sensitive in there, censor any account names if you want, and post the log here.

If you're the problem only occurs when importing accounts then do that instead. Also please specify how many accounts you're importing.

NOTE: This app is only meant to be used with an account you own, using it with invalid account details might cause Valve to temporarily block any further login attempts!

**Comment by T4lk** [comment]
had same issue launched with admin rights fixed the issue

**Comment by dumbasPL** [comment]
> had same issue launched with admin rights fixed the issue

Weird, this program shouldn't require admin rights for anything. If you don't mind then try to get the error log like I described above when **not** running as admin. I would love to know what the cause is and maybe fix it.

**Comment by T4lk** [comment]
seems like just nothing happens no idea
![image](https://github.com/dumbasPL/csgo-checker/assets/76187598/3826379b-c744-444f-b916-43724398a838)
this only works on accounts that are getting added for the first time, if u add it with admin rights it will work normally

**Comment by T4lk** [comment]
![image](https://github.com/dumbasPL/csgo-checker/assets/76187598/67bbca7b-a97b-4e9a-a12d-b06d37ae61f9)
seems like it only happens with steam accounts that have the steam mobile authenticator

**Comment by dumbasPL** [comment]
So it breaks when you add an account that has steam mobile authenticator without admin, correct?

**Comment by T4lk** [comment]
yes

**Comment by dumbasPL** [comment]
An update has been released, I haven't done anything specific related to this issue, but please try it and see if the problem still exists. It might have been fixed as a result of one of the dependencies being updated.
